config/routes.rb
Rails.application.routes.draw do
  resources :tickets, except: [:index, :destroy] 
  resources :events, except: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets
  validates :name, :date, :city, :state, :country, :image, presence: true

  def self.next
    where('date >= ?', Time.zone.now)
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  accepts_nested_attributes_for :event

  def self.get_from_event(event)
    where(event_id: event.id).order('value ASC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.next
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @tickets = Ticket.get_from_event @event
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :city, :state, :country, :image)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:description, :quantity, :value, :email, :active, :profiles, :event_id)
    end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :get_events, only: [:new, :edit]

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @errors = []

    unless @ticket.event_id?
      event = Event.new(event_params)
      if (event.save)
        @ticket.event_id = event.id
      else
        @errors = event.errors
      end
    end

    respond_to do |format|
      if @errors.empty? &&
         @ticket.save
        format.html { redirect_to @ticket.event, notice: 'Ingresso(s) anunciado(s) com sucesso.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        @errors = @ticket.errors unless @ticket.errors.empty?
        get_events
        format.html { render :new }
        format.json { render json: @errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket.event, notice: 'Ingresso(s) atualizado(s) com sucesso.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        get_events
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:description, :quantity, :value, :email, :active, :profiles, :event_id)
    end

    def event_params
      params.require(:event).permit(:name, :date, :city, :state, :country, :image)
    end


    def get_events
      @events = Event.all.next
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form.fields_for :event do |fevent| %>
<div class="form-group">
    <%= fevent.label :name, 'Nome' %>
    <%= fevent.text_field :name, id: :event_name, class: 'fevent.control' %>
</div>

<div class="form-group">
    <%= fevent.label :date, 'Data' %>
    <%= fevent.text_field :date, id: :event_date, class: 'fevent.control' %>
</div>

<div class="form-group">
    <%= fevent.label :city, 'Cidade' %>
    <%= fevent.text_field :city, id: :event_city, class: 'fevent.control' %>
</div>

<div class="form-group">
    <%= fevent.label :state, 'Estado' %>
    <%= fevent.text_field :state, id: :event_state, class: 'fevent.control' %>
</div>

<div class="form-group">
    <%= fevent.label :country, 'País' %>
    <%= fevent.text_field :country, id: :event_country, class: 'fevent.control' %>
</div>

<div class="form-group">
    <%= fevent.label :image, 'Imagem (url completa)' %>
    <%= fevent.text_field :image, id: :event_image, class: 'fevent.control' %>
</div>
<% end %>

app/views/events/index.html.erb
<%= stylesheet_link_tag 'events', media: 'all', 'data-turbolinks-track': 'reload' %>

<p id="notice"><%= notice %></p>

<div class="row">
    <% @events.each do |event| %>
      <div class="col-lg-3 col-md-4 col-sm-6 events-item">
        <div class="card h-100">
          <%= link_to(event) do %>
            <%= image_tag(event.image) %>
          <% end %>
          <div class="card-body">
            <h4 class="card-title"><%= link_to event.name, event %></h4>
          </div>
          <p class="card-text">
            <%= event.date %> em <%= event.city %>/<%= event.state %> (<%= event.country %>)
          </p>
        </div>
      </div>
    <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%= stylesheet_link_tag 'events', media: 'all', 'data-turbolinks-track': 'reload' %>

<% if notice %>
<span id="notice" class="alert alert-info"><%= notice %></span>
<% end %>

<div class='event-header' style='background-image: url(<%= @event.image %>)'>
  <h1><%= @event.name %></h1>
  <small><%= @event.date %></small><br/>
  <small><%= @event.city %>/<%= @event.state %> (<%= @event.country %>)</small>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Ingresso</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Valor unitário</th>
      <th scope="col">Email</th>
      <th scope="col">Perfis</th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.description %></td>
        <td><%= ticket.quantity %></td>
        <td><%= ticket.value %></td>
        <td><%= ticket.email %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compreinaovou2</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Alterar anúncio</a></li>
            <li><a href="#">Como funciona</a></li>
            <li><a href="#">Aviso legal</a></li>
            <li><a href="#">Sobre</a></li>
            <li><a href="#">Contato</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="brand">
        <a href="/"><label class="first">Comprei e</label><span>NAO</span><label class="second">vou</label></a>
    </div>

    <div class="container">
      <div class="anuncie">
        <%= link_to 'Anuncie seu ingresso!', new_ticket_path, class: 'btn btn-danger pull-right btn-xlarge' %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if @errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Evento</legend>

    <div class="form-group" id="evento-existente">
      <%= form.collection_select :event_id, @events, :id, :name, { prompt: true }, { id: :ticket_event_id, class: 'form-control' } %>
        <small class="pull-right"><a href="#" id="habilitar-evento-novo">Quero cadastrar um novo evento!</a></small>
    </div>

    <div id="evento-novo" class="hide">
       <%= fields_for :event do |fields_event| %>

           <div class="form-group">
                <%= fields_event.label :name, 'Nome' %>
                <%= fields_event.text_field :name, id: :event_name, class: 'form-control' %>
           </div>

           <div class="form-group">
                <%= fields_event.label :date, 'Data' %>
                <%= fields_event.text_field :date, id: :event_date, class: 'form-control' %>
           </div>

           <div class="form-group">
               <%= fields_event.label :city, 'Cidade' %>
               <%= fields_event.text_field :city, id: :event_city, class: 'form-control' %>
           </div>

            <div class="form-group">
                <%= fields_event.label :state, 'Estado' %>
                <%= fields_event.text_field :state, id: :event_state, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= fields_event.label :country, 'País' %>
                <%= fields_event.text_field :country, id: :event_country, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= fields_event.label :image, 'Imagem (url completa)' %>
                <%= fields_event.text_field :image, id: :event_image, class: 'form-control' %>
            </div>
        <% end %>

    </div>
  </fieldset>

  <fieldset>
      <legend>Ingresso</legend>

      <div class="form-group">
        <%= form.label :description, 'Descrição (meia entrada, inteira, passe para dias, etc)' %>
        <%= form.text_field :description, id: :ticket_description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :quantity, 'Quantidade' %>
        <%= form.number_field :quantity, id: :ticket_quantity, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :value, 'Valor unitário' %>
        <%= form.text_field :value, id: :ticket_value, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :email, 'Email' %>
        <%= form.text_field :email, id: :ticket_email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :profiles, 'Twitter, Facebook, Instagram, etc.' %>
        <%= form.text_field :profiles, id: :ticket_profiles, class: 'form-control' %>
    </div>
  </fieldset>

  <div class="actions">
    <%= form.submit 'Anunciar', { class: 'btn btn-primary pull-right' } %>
  </div>
<% end %>

<%= javascript_include_tag 'tickets', 'data-turbolinks-track': 'reload' %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/new.html.erb
<h1>Anuncie seu ingresso!</h1>

<%= render 'form', ticket: @ticket %>